import { ThreadsService as GeneratedThreadsService, type ThreadMessageResponseDto, type ListThreadMessagesResponseDto } from "@taico/client";
import type { ThreadListItem, Thread } from './types';

// Wrapper around autogenerated API client
export class ThreadsService {
  static async listThreads(): Promise<{ items: ThreadListItem[] }> {
    const response = await GeneratedThreadsService.threadsControllerListThreads();
    return { items: response.items };
  }

  static async getThread(id: string): Promise<Thread> {
    return await GeneratedThreadsService.threadsControllerGetThread(id);
  }

  static async createThread(title?: string): Promise<Thread> {
    return await GeneratedThreadsService.threadsControllerCreateThread({ title });
  }

  static async deleteThread(id: string): Promise<void> {
    await GeneratedThreadsService.threadsControllerDeleteThread(id);
  }

  static async listMessages(threadId: string, page: number = 1, limit: number = 50): Promise<ListThreadMessagesResponseDto> {
    return await GeneratedThreadsService.threadsControllerListMessages(threadId, page, limit);
  }

  static async createMessage(threadId: string, content: string): Promise<ThreadMessageResponseDto> {
    return await GeneratedThreadsService.threadsControllerCreateMessage(threadId, { content });
  }
}
