import { ThreadsService as GeneratedThreadsService } from "@taico/client";
import type { ThreadListItem, Thread } from './types';

// Wrapper around autogenerated API client
export class ThreadsService {
  static async listThreads(): Promise<{ items: ThreadListItem[] }> {
    const response = await GeneratedThreadsService.threadsControllerListThreads();
    return { items: response.items };
  }

  static async getThread(id: string): Promise<Thread> {
    return await GeneratedThreadsService.threadsControllerGetThread(id);
  }

  static async deleteThread(id: string): Promise<void> {
    await GeneratedThreadsService.threadsControllerDeleteThread(id);
  }
}
