apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: env
    envs:
      - env.env

resources:
- ../../base

replacements:
  # Replace STORAGE_PATH in volume hostPath
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.STORAGE_PATH
    targets:
      - select:
          kind: Deployment
          name: taico
        fieldPaths:
          - spec.template.spec.volumes.[name=data].hostPath.path
  # Replace ADK_URL in taico-config ConfigMap
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.ADK_URL
    targets:
      - select:
          kind: ConfigMap
          name: taico-config
        fieldPaths:
          - data.ADK_URL
  # Replace OLLAMA_URL in taico-config ConfigMap
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.OLLAMA_URL
    targets:
      - select:
          kind: ConfigMap
          name: taico-config
        fieldPaths:
          - data.OLLAMA_URL
  # Replace SECRETS_ENABLED in taico-config ConfigMap
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.SECRETS_ENABLED
    targets:
      - select:
          kind: ConfigMap
          name: taico-config
        fieldPaths:
          - data.SECRETS_ENABLED
  # Replace ALLOW_PLAINTEXT_SECRETS_INSECURE in taico-config ConfigMap
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.ALLOW_PLAINTEXT_SECRETS_INSECURE
    targets:
      - select:
          kind: ConfigMap
          name: taico-config
        fieldPaths:
          - data.ALLOW_PLAINTEXT_SECRETS_INSECURE
  # Replace ISSUER_URL in taico-config ConfigMap
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.ISSUER_URL
    targets:
      - select:
          kind: ConfigMap
          name: taico-config
        fieldPaths:
          - data.ISSUER_URL
