export enum TaskExecutionStatus {
  READY = 'READY',
  CLAIMED = 'CLAIMED',
  RUNNING = 'RUNNING',
  STOP_REQUESTED = 'STOP_REQUESTED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  STALE = 'STALE',
}
