import { ErrorCodes } from "@taico/errors";

export const ErrorCatalog: Record<
  string,
  {
    status: number;
    title: string;
    type: string;
    retryable?: boolean;
  }
> = {
  [ErrorCodes.TASK_NOT_FOUND]: {
    status: 404,
    title: 'Task not found',
    type: '/errors/tasks/not-found',
    retryable: false,
  },
  [ErrorCodes.TASK_NOT_ASSIGNED]: {
    status: 400,
    title: 'Task not assigned',
    type: '/errors/tasks/not-assigned',
    retryable: false,
  },
  [ErrorCodes.INVALID_STATUS_TRANSITION]: {
    status: 400,
    title: 'Invalid status transition',
    type: '/errors/tasks/invalid-status-transition',
    retryable: false,
  },
  [ErrorCodes.COMMENT_REQUIRED]: {
    status: 400,
    title: 'Comment required',
    type: '/errors/tasks/comment-required',
    retryable: false,
  },
  [ErrorCodes.TASK_IS_THREAD_PARENT]: {
    status: 400,
    title: 'Task is thread parent',
    type: '/errors/tasks/is-thread-parent',
    retryable: false,
  },
  [ErrorCodes.INPUT_REQUEST_SELF_ASSIGNMENT]: {
    status: 400,
    title: 'Input request cannot target asker',
    type: '/errors/tasks/input-request-self-assignment',
    retryable: false,
  },
  [ErrorCodes.TASK_BLUEPRINT_NOT_FOUND]: {
    status: 404,
    title: 'Task blueprint not found',
    type: '/errors/task-blueprints/not-found',
    retryable: false,
  },
  [ErrorCodes.TASK_BLUEPRINT_HAS_ACTIVE_SCHEDULES]: {
    status: 409,
    title: 'Task blueprint has active schedules',
    type: '/errors/task-blueprints/has-active-schedules',
    retryable: false,
  },
  [ErrorCodes.SCHEDULED_TASK_NOT_FOUND]: {
    status: 404,
    title: 'Scheduled task not found',
    type: '/errors/scheduled-tasks/not-found',
    retryable: false,
  },
  [ErrorCodes.INVALID_CRON_EXPRESSION]: {
    status: 400,
    title: 'Invalid cron expression',
    type: '/errors/scheduled-tasks/invalid-cron',
    retryable: false,
  },
  [ErrorCodes.PAGE_NOT_FOUND]: {
    status: 404,
    title: 'Context page not found',
    type: '/errors/wiki/page-not-found',
    retryable: false,
  },
  [ErrorCodes.PARENT_PAGE_NOT_FOUND]: {
    status: 404,
    title: 'Parent page not found',
    type: '/errors/wiki/parent-page-not-found',
    retryable: false,
  },
  [ErrorCodes.CIRCULAR_REFERENCE]: {
    status: 400,
    title: 'Circular reference detected',
    type: '/errors/wiki/circular-reference',
    retryable: false,
  },
  [ErrorCodes.BLOCK_IS_THREAD_STATE]: {
    status: 400,
    title: 'Context block is thread state',
    type: '/errors/context/block-is-thread-state',
    retryable: false,
  },
  [ErrorCodes.BLOCK_HAS_CHILDREN]: {
    status: 409,
    title: 'Context block has children',
    type: '/errors/context/block-has-children',
    retryable: false,
  },
  [ErrorCodes.AGENT_NOT_FOUND]: {
    status: 404,
    title: 'Agent not found',
    type: '/errors/agents/not-found',
    retryable: false,
  },
  [ErrorCodes.AGENT_SLUG_CONFLICT]: {
    status: 409,
    title: 'Agent slug conflict',
    type: '/errors/agents/slug-conflict',
    retryable: false,
  },
  [ErrorCodes.AGENT_TOOL_PERMISSION_NOT_FOUND]: {
    status: 404,
    title: 'Agent tool permission not found',
    type: '/errors/agents/tool-permission-not-found',
    retryable: false,
  },
  [ErrorCodes.AGENT_RUN_NOT_FOUND]: {
    status: 404,
    title: 'Agent run not found',
    type: '/errors/agent-runs/not-found',
    retryable: false,
  },
  [ErrorCodes.TASK_EXECUTION_NOT_FOUND]: {
    status: 404,
    title: 'Task execution not found',
    type: '/errors/executions/not-found',
    retryable: false,
  },
  [ErrorCodes.CLIENT_ALREADY_REGISTERED]: {
    status: 409,
    title: 'Client already registered',
    type: '/errors/authz/client-already-registered',
    retryable: false,
  },
  [ErrorCodes.CLIENT_NOT_FOUND]: {
    status: 404,
    title: 'Client not found',
    type: '/errors/authz/client-not-found',
    retryable: false,
  },
  [ErrorCodes.INVALID_REDIRECT_URI]: {
    status: 400,
    title: 'Invalid redirect URI',
    type: '/errors/authz/invalid-redirect-uri',
    retryable: false,
  },
  [ErrorCodes.INVALID_GRANT_TYPE]: {
    status: 400,
    title: 'Invalid grant type',
    type: '/errors/authz/invalid-grant-type',
    retryable: false,
  },
  [ErrorCodes.INVALID_TOKEN_ENDPOINT_AUTH_METHOD]: {
    status: 400,
    title: 'Invalid token endpoint authentication method',
    type: '/errors/authz/invalid-token-endpoint-auth-method',
    retryable: false,
  },
  [ErrorCodes.MISSING_REQUIRED_FIELD]: {
    status: 400,
    title: 'Missing required field',
    type: '/errors/authz/missing-required-field',
    retryable: false,
  },
  [ErrorCodes.SERVER_NOT_FOUND]: {
    status: 404,
    title: 'MCP server not found',
    type: '/errors/mcp/server-not-found',
    retryable: false,
  },
  [ErrorCodes.SERVER_ALREADY_EXISTS]: {
    status: 409,
    title: 'MCP server already exists',
    type: '/errors/mcp/server-already-exists',
    retryable: false,
  },
  [ErrorCodes.SCOPE_NOT_FOUND]: {
    status: 404,
    title: 'MCP scope not found',
    type: '/errors/mcp/scope-not-found',
    retryable: false,
  },
  [ErrorCodes.SCOPE_ALREADY_EXISTS]: {
    status: 409,
    title: 'MCP scope already exists',
    type: '/errors/mcp/scope-already-exists',
    retryable: false,
  },
  [ErrorCodes.CONNECTION_NOT_FOUND]: {
    status: 404,
    title: 'MCP connection not found',
    type: '/errors/mcp/connection-not-found',
    retryable: false,
  },
  [ErrorCodes.CONNECTION_NAME_CONFLICT]: {
    status: 409,
    title: 'Connection name conflict',
    type: '/errors/mcp/connection-name-conflict',
    retryable: false,
  },
  [ErrorCodes.MAPPING_NOT_FOUND]: {
    status: 404,
    title: 'MCP mapping not found',
    type: '/errors/mcp/mapping-not-found',
    retryable: false,
  },
  [ErrorCodes.SERVER_HAS_DEPENDENCIES]: {
    status: 409,
    title: 'Server has dependencies',
    type: '/errors/mcp/server-has-dependencies',
    retryable: false,
  },
  [ErrorCodes.SCOPE_HAS_MAPPINGS]: {
    status: 409,
    title: 'Scope has mappings',
    type: '/errors/mcp/scope-has-mappings',
    retryable: false,
  },
  [ErrorCodes.CONNECTION_HAS_MAPPINGS]: {
    status: 409,
    title: 'Connection has mappings',
    type: '/errors/mcp/connection-has-mappings',
    retryable: false,
  },
  [ErrorCodes.INVALID_MAPPING]: {
    status: 400,
    title: 'Invalid mapping',
    type: '/errors/mcp/invalid-mapping',
    retryable: false,
  },
  [ErrorCodes.AUTH_FLOW_NOT_FOUND]: {
    status: 404,
    title: 'Authorization flow not found',
    type: '/errors/authz/flow-not-found',
    retryable: false,
  },
  [ErrorCodes.AUTH_FLOW_ALREADY_COMPLETED]: {
    status: 401,
    title: 'Authorization flow already completed',
    type: '/errors/authz/flow-already-completed',
    retryable: false,
  },
  [ErrorCodes.INVALID_FLOW_STATE]: {
    status: 400,
    title: 'Invalid flow state',
    type: '/errors/authz/invalid-flow-state',
    retryable: false,
  },
  [ErrorCodes.SERVER_IDENTIFIER_MISMATCH]: {
    status: 400,
    title: 'Server identifier mismatch',
    type: '/errors/authz/server-identifier-mismatch',
    retryable: false,
  },
  [ErrorCodes.DOWNSTREAM_AUTH_FAILED]: {
    status: 400,
    title: 'Downstream authorization failed',
    type: '/errors/authz/downstream-auth-failed',
    retryable: false,
  },
  [ErrorCodes.NO_PENDING_CONNECTION_FLOWS]: {
    status: 400,
    title: 'No pending connection flows',
    type: '/errors/authz/no-pending-connection-flows',
    retryable: false,
  },
  [ErrorCodes.CONNECTION_FLOW_NOT_FOUND]: {
    status: 404,
    title: 'Connection flow not found',
    type: '/errors/authz/connection-flow-not-found',
    retryable: false,
  },
  [ErrorCodes.TOKEN_EXCHANGE_FAILED]: {
    status: 400,
    title: 'Token exchange failed',
    type: '/errors/authz/token-exchange-failed',
    retryable: false,
  },
  [ErrorCodes.INVALID_AUTHORIZATION_CODE]: {
    status: 401,
    title: 'Invalid authorization code',
    type: '/errors/token/invalid-authorization-code',
    retryable: false,
  },
  [ErrorCodes.CLIENT_ID_MISMATCH]: {
    status: 401,
    title: 'Client ID mismatch',
    type: '/errors/token/client-id-mismatch',
    retryable: false,
  },
  [ErrorCodes.AUTHORIZATION_CODE_USED]: {
    status: 401,
    title: 'Authorization code already used',
    type: '/errors/token/authorization-code-used',
    retryable: false,
  },
  [ErrorCodes.AUTHORIZATION_CODE_EXPIRED]: {
    status: 401,
    title: 'Authorization code expired',
    type: '/errors/token/authorization-code-expired',
    retryable: false,
  },
  [ErrorCodes.REDIRECT_URI_MISMATCH]: {
    status: 400,
    title: 'Redirect URI mismatch',
    type: '/errors/token/redirect-uri-mismatch',
    retryable: false,
  },
  [ErrorCodes.MISSING_PKCE_PARAMETERS]: {
    status: 400,
    title: 'Missing PKCE parameters',
    type: '/errors/token/missing-pkce-parameters',
    retryable: false,
  },
  [ErrorCodes.INVALID_CODE_VERIFIER]: {
    status: 401,
    title: 'Invalid code verifier',
    type: '/errors/token/invalid-code-verifier',
    retryable: false,
  },
  [ErrorCodes.INVALID_REFRESH_TOKEN]: {
    status: 401,
    title: 'Invalid refresh token',
    type: '/errors/token/invalid-refresh-token',
    retryable: false,
  },
  [ErrorCodes.REFRESH_TOKEN_EXPIRED]: {
    status: 401,
    title: 'Refresh token expired',
    type: '/errors/token/refresh-token-expired',
    retryable: false,
  },
  [ErrorCodes.REFRESH_TOKEN_REVOKED]: {
    status: 401,
    title: 'Refresh token revoked',
    type: '/errors/token/refresh-token-revoked',
    retryable: false,
  },
  [ErrorCodes.MISSING_ACCESS_TOKEN]: {
    status: 401,
    title: 'Missing access token',
    type: '/errors/auth/missing-access-token',
    retryable: false,
  },
  [ErrorCodes.INVALID_ACCESS_TOKEN]: {
    status: 401,
    title: 'Invalid access token',
    type: '/errors/auth/invalid-access-token',
    retryable: false,
  },
  [ErrorCodes.INSUFFICIENT_SCOPE]: {
    status: 403,
    title: 'Insufficient scope',
    type: '/errors/auth/insufficient-scope',
    retryable: false,
  },
  [ErrorCodes.VALIDATION_FAILED]: {
    status: 400,
    title: 'Validation failed',
    type: '/errors/validation/failed',
    retryable: false,
  },
  [ErrorCodes.INTERNAL_ERROR]: {
    status: 500,
    title: 'Internal server error',
    type: '/errors/internal',
    retryable: true,
  },
  [ErrorCodes.SECRET_NOT_FOUND]: {
    status: 404,
    title: 'Secret not found',
    type: '/errors/secrets/not-found',
    retryable: false,
  },
  [ErrorCodes.SECRET_NAME_CONFLICT]: {
    status: 409,
    title: 'Secret name conflict',
    type: '/errors/secrets/name-conflict',
    retryable: false,
  },
  [ErrorCodes.SECRET_FEATURE_DISABLED]: {
    status: 503,
    title: 'Secrets feature is disabled',
    type: '/errors/secrets/feature-disabled',
    retryable: false,
  },
  [ErrorCodes.USER_NOT_FOUND]: {
    status: 404,
    title: 'User not found',
    type: '/errors/identity-provider/user-not-found',
    retryable: false,
  },
  [ErrorCodes.USER_EMAIL_CONFLICT]: {
    status: 409,
    title: 'Email address already in use',
    type: '/errors/identity-provider/email-conflict',
    retryable: false,
  },
  [ErrorCodes.USER_SLUG_CONFLICT]: {
    status: 409,
    title: 'Username already taken',
    type: '/errors/identity-provider/slug-conflict',
    retryable: false,
  },
  [ErrorCodes.PASSWORD_TOO_SHORT]: {
    status: 400,
    title: 'Password too short',
    type: '/errors/identity-provider/password-too-short',
    retryable: false,
  },
  [ErrorCodes.ONBOARDING_NOT_ALLOWED]: {
    status: 409,
    title: 'Onboarding not allowed',
    type: '/errors/identity-provider/onboarding-not-allowed',
    retryable: false,
  },
  [ErrorCodes.INVALID_CREDENTIALS]: {
    status: 401,
    title: 'Invalid credentials',
    type: '/errors/identity-provider/invalid-credentials',
    retryable: false,
  },
  [ErrorCodes.INVALID_CURRENT_PASSWORD]: {
    status: 401,
    title: 'Current password is incorrect',
    type: '/errors/identity-provider/invalid-current-password',
    retryable: false,
  },
  [ErrorCodes.CHAT_PROVIDER_NOT_FOUND]: {
    status: 404,
    title: 'Chat provider not found',
    type: '/errors/chat-providers/not-found',
    retryable: false,
  },
  [ErrorCodes.CHAT_PROVIDER_ALREADY_ACTIVE]: {
    status: 409,
    title: 'Another chat provider is already active',
    type: '/errors/chat-providers/already-active',
    retryable: false,
  },
  [ErrorCodes.CHAT_PROVIDER_NOT_CONFIGURED]: {
    status: 400,
    title: 'Chat provider is not fully configured',
    type: '/errors/chat-providers/not-configured',
    retryable: false,
  },
  [ErrorCodes.NO_ACTIVE_CHAT_PROVIDER]: {
    status: 503,
    title: 'No active chat provider configured',
    type: '/errors/chat-providers/no-active-provider',
    retryable: false,
  },
};
