export {
  INTERNAL_WORKER_AUTH_SCOPES,
  INTERNAL_WORKER_AUTH_TARGET_DESCRIPTION,
  INTERNAL_WORKER_AUTH_TARGET_ID,
  INTERNAL_WORKER_AUTH_TARGET_NAME,
  INTERNAL_WORKER_AUTH_TARGET_VERSION,
} from '@taico/shared';
