export const ErrorCodes = {
  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COMMENT_REQUIRED: 'COMMENT_REQUIRED',
  TASK_IS_THREAD_PARENT: 'TASK_IS_THREAD_PARENT',
  INPUT_REQUEST_SELF_ASSIGNMENT: 'INPUT_REQUEST_SELF_ASSIGNMENT',

  // Task Blueprint errors
  TASK_BLUEPRINT_NOT_FOUND: 'TASK_BLUEPRINT_NOT_FOUND',
  TASK_BLUEPRINT_HAS_ACTIVE_SCHEDULES: 'TASK_BLUEPRINT_HAS_ACTIVE_SCHEDULES',
  SCHEDULED_TASK_NOT_FOUND: 'SCHEDULED_TASK_NOT_FOUND',
  INVALID_CRON_EXPRESSION: 'INVALID_CRON_EXPRESSION',

  // Context errors
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  PARENT_PAGE_NOT_FOUND: 'PARENT_PAGE_NOT_FOUND',
  CIRCULAR_REFERENCE: 'CIRCULAR_REFERENCE',
  BLOCK_IS_THREAD_STATE: 'BLOCK_IS_THREAD_STATE',

  // Agent errors
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_SLUG_CONFLICT: 'AGENT_SLUG_CONFLICT',

  // Agent Run errors
  AGENT_RUN_NOT_FOUND: 'AGENT_RUN_NOT_FOUND',

  // Execution errors
  TASK_EXECUTION_NOT_FOUND: 'TASK_EXECUTION_NOT_FOUND',
  TASK_EXECUTION_NOT_CLAIMABLE: 'TASK_EXECUTION_NOT_CLAIMABLE',
  TASK_EXECUTION_ALREADY_CLAIMED: 'TASK_EXECUTION_ALREADY_CLAIMED',

  // Chat errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  ADK_SESSION_CREATION_FAILED: 'ADK_SESSION_CREATION_FAILED',

  // Chat Provider errors
  CHAT_PROVIDER_NOT_FOUND: 'CHAT_PROVIDER_NOT_FOUND',
  CHAT_PROVIDER_ALREADY_ACTIVE: 'CHAT_PROVIDER_ALREADY_ACTIVE',
  CHAT_PROVIDER_NOT_CONFIGURED: 'CHAT_PROVIDER_NOT_CONFIGURED',
  NO_ACTIVE_CHAT_PROVIDER: 'NO_ACTIVE_CHAT_PROVIDER',

  // Authorization Server - Client Registration errors
  CLIENT_ALREADY_REGISTERED: 'CLIENT_ALREADY_REGISTERED',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  INVALID_REDIRECT_URI: 'INVALID_REDIRECT_URI',
  INVALID_GRANT_TYPE: 'INVALID_GRANT_TYPE',
  INVALID_TOKEN_ENDPOINT_AUTH_METHOD: 'INVALID_TOKEN_ENDPOINT_AUTH_METHOD',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Tools errors
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  SERVER_ALREADY_EXISTS: 'SERVER_ALREADY_EXISTS',
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',
  SCOPE_ALREADY_EXISTS: 'SCOPE_ALREADY_EXISTS',
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  CONNECTION_NAME_CONFLICT: 'CONNECTION_NAME_CONFLICT',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',
  SERVER_HAS_DEPENDENCIES: 'SERVER_HAS_DEPENDENCIES',
  SCOPE_HAS_MAPPINGS: 'SCOPE_HAS_MAPPINGS',
  CONNECTION_HAS_MAPPINGS: 'CONNECTION_HAS_MAPPINGS',
  INVALID_MAPPING: 'INVALID_MAPPING',

  // Authorization flow errors
  AUTH_FLOW_NOT_FOUND: 'AUTH_FLOW_NOT_FOUND',
  AUTH_FLOW_ALREADY_COMPLETED: 'AUTH_FLOW_ALREADY_COMPLETED',
  INVALID_FLOW_STATE: 'INVALID_FLOW_STATE',
  SERVER_IDENTIFIER_MISMATCH: 'SERVER_IDENTIFIER_MISMATCH',
  DOWNSTREAM_AUTH_FAILED: 'DOWNSTREAM_AUTH_FAILED',
  NO_PENDING_CONNECTION_FLOWS: 'NO_PENDING_CONNECTION_FLOWS',
  CONNECTION_FLOW_NOT_FOUND: 'CONNECTION_FLOW_NOT_FOUND',
  TOKEN_EXCHANGE_FAILED: 'TOKEN_EXCHANGE_FAILED',

  // Token errors
  INVALID_AUTHORIZATION_CODE: 'INVALID_AUTHORIZATION_CODE',
  CLIENT_ID_MISMATCH: 'CLIENT_ID_MISMATCH',
  AUTHORIZATION_CODE_USED: 'AUTHORIZATION_CODE_USED',
  AUTHORIZATION_CODE_EXPIRED: 'AUTHORIZATION_CODE_EXPIRED',
  REDIRECT_URI_MISMATCH: 'REDIRECT_URI_MISMATCH',
  MISSING_PKCE_PARAMETERS: 'MISSING_PKCE_PARAMETERS',
  INVALID_CODE_VERIFIER: 'INVALID_CODE_VERIFIER',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN_SIGNATURE: 'INVALID_TOKEN_SIGNATURE',
  MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',

  // Secret errors
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',
  SECRET_NAME_CONFLICT: 'SECRET_NAME_CONFLICT',
  SECRET_FEATURE_DISABLED: 'SECRET_FEATURE_DISABLED',

  // Identity Provider errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_CONFLICT: 'USER_EMAIL_CONFLICT',
  USER_SLUG_CONFLICT: 'USER_SLUG_CONFLICT',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  ONBOARDING_NOT_ALLOWED: 'ONBOARDING_NOT_ALLOWED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // Generic errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
