apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taico
  namespace: taico
spec:
  dnsNames:
    - taico.app
  secretName: taico-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
