apiVersion: v1
kind: ConfigMap
metadata:
  name: taico-config
  namespace: taico
data:
  # NODE_ENV defaults to production (no need to set explicitly)
  BACKEND_PORT: "3000"
  SECRETS_ENABLED: "true"
  ALLOW_PLAINTEXT_SECRETS_INSECURE: "true"
  ISSUER_URL: PLACEHOLDER_ISSUER_URL
  DATABASE_PATH: "/app/data/database.sqlite"
  GOOGLE_GENAI_USE_VERTEXAI: "True"
  GOOGLE_CLOUD_PROJECT: "placeholder"
  GOOGLE_CLOUD_LOCATION: "placeholder"
  GOOGLE_APPLICATION_CREDENTIALS: "/placeholder/foo.json"
