apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taico
  namespace: taico
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - taico.app
      secretName: taico-tls
  rules:
    - host: taico.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taico
                port:
                  number: 80
