apiVersion: v1
kind: Service
metadata:
  name: taico-codex
  namespace: taico-codex
  labels:
    app: taico-codex
spec:
  type: ClusterIP
  selector:
    app: taico-codex
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
